application: kyotoxbus
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /intro.*
  static_files: static/intro.html
  upload: static/intro.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon.png
  static_files: static/icon4.png
  upload: static/icon4.png

- url: /cache.manifest
  static_files: static/cache.manifest
  mime_type: text/cache-manifest
  upload: static/cache.manifest
  expiration: '0'

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google539e02a4f6c950a3.html
  static_files: static/google539e02a4f6c950a3.html
  upload: static/google539e02a4f6c950a3.html

- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/warmup.*
  script: warmup.py

- url: /.*
  script: main.py

libraries:
- name: django
  version: '1.2'

inbound_services:
- warmup
