application: kyoto-bus
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /intro.*
  static_files: static/intro.html
  upload: static/intro.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /cache.manifest
  static_files: static/cache.manifest
  mime_type: text/cache-manifest
  upload: static/cache.manifest
  expiration: '0'

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/warmup.*
  script: warmup.py

- url: /.*
  script: main.py

inbound_services:
- warmup
